### ISSUE TITLE
Is requirement `9.0 <= a && a <= 9.0` in function `triangle` a typo?

### ISSUE THREAD

**Issue by KomaGR** [malyzajko/rosa#5]
Or is `a` really is required to be both `9.0 <= a` and `a <= 9.0`?
https://github.com/malyzajko/rosa/blob/68e58b8c2f334ddde0f7647dc2d9c9ecc30309af/testcases/real/popl2014/TriangleProgression.scala#L5-L8

**Comment by malyzajko** [comment]
It's not a typo, but one way of assigning 'a' a constant value. 
(Btw. unless you need Rosa's functionality regarding conditionals and loops, the Daisy project is currently being actively developed: https://github.com/malyzajko/daisy)

**Comment by KomaGR** [comment]
Thanks for the quick reply. 
I'm actually using [FPBench](https://github.com/FPBench/FPBench) (which also includes Daisy benchmarks) and encountered [this](https://github.com/FPBench/FPBench/blob/3143f5d46ed1a40908b184ba5cb5c7d4e09fbf77/benchmarks/rosa.fpcore#L212-L217) precondition, and I followed it here to verify.

**Comment by malyzajko** [comment]
I see, no typo :-)
